import type { NextPage } from 'next';
import Head from 'next/head';
import { increment, decrement, counter } from '../store/counterSlice';
import { useAppDispatch, useAppSelector } from '../store/hooks';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const dispatch = useAppDispatch();
  const { value } = useAppSelector(counter);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className={styles.title}>{value}</h1>
        <button
          onClick={() => dispatch(increment())}
          style={{
            margin: '1rem',
            padding: '1rem',
            border: '1px solid black',
            minWidth: '100px',
            fontSize: '1.5rem',
            backgroundColor: 'transparent',
          }}
        >
          Increase
        </button>
        <button
          onClick={() => dispatch(decrement())}
          style={{
            margin: '1rem',
            padding: '1rem',
            border: '1px solid black',
            minWidth: '100px',
            fontSize: '1.5rem',
            backgroundColor: 'transparent',
          }}
        >
          Decrease
        </button>
      </main>
    </div>
  );
};

export default Home;
